# syntax=docker/dockerfile:1.0.0-experimental

# Build command requires docker build kit and ssh key path
# docker build -t giffy-lambda -f Dockerfile.lambda .

FROM public.ecr.aws/lambda/python:3.8

# Copy package
COPY . ${LAMBDA_TASK_ROOT}
RUN chmod -R 755 ${LAMBDA_TASK_ROOT}

# Install dependencies
RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

CMD ["lambda_handler.handler"]
