name: Documentation

on: pull_request

jobs:
  make-pages:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
    - name: install sphinx dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install sphinx
        python -m pip install sphinx_rtd_theme
        python -m pip install sphinx-click
    - name: build documentation
      run: |
        cd docs
        make html
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        force_orphan: true
        full_commit_message: ${{ github.event.head_commit.message }}
