name: Documentation

on:
  push:
    branches: [main, master]

jobs:
  make-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: select python version
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: checkout nsrdb
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          path: nsrdb
      - name: checkout mlclouds
        uses: actions/checkout@v2
        with:
          repository: nrel/mlclouds
          ssh-key: ${{ secrets.SSH_KEY }}
          path: mlclouds
      - name: checkout rest2
        uses: actions/checkout@v2
        with:
          repository: nrel/rest2
          ssh-key: ${{ secrets.SSH_KEY }}
          path: rest2
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install rest2 dependencies
        working-directory: ./rest2
        shell: bash -l {0}
        run: |
          conda install pip
          pip install -e .
      - name: Install nsrdb dependencies
        working-directory: ./nsrdb
        shell: bash -l {0}
        run: |
          conda install hdf4
          conda install -c conda-forge pyhdf
          pip install -e .
      - name: Install mlclouds dependencies
        working-directory: ./mlclouds
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: install sphinx dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install sphinx
          python -m pip install sphinx_rtd_theme
          python -m pip install sphinx-click
      - name: build documentation
        run: |
          cd docs
          make html
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
