name: Pytests

on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
        include:
          - os: ubuntu-latest
            python-version: 3.9
          - os: ubuntu-latest
            python-version: 3.7
          - os: ubuntu-latest
            python-version: 3.6

    steps:
    - name: checkout nsrdb
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        path: nsrdb
    - name: checkout mlclouds
      uses: actions/checkout@v2
      with:
        repository: nrel/mlclouds
        ssh-key: ${{ secrets.SSH_KEY }}
        path: mlclouds
    - name: checkout rest2
      uses: actions/checkout@v2
      with:
        repository: nrel/rest2
        ssh-key: ${{ secrets.SSH_KEY }}
        path: rest2
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install rest2 dependencies
      working-directory: ./rest2
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: Install nsrdb dependencies
      working-directory: ./nsrdb
      shell: bash -l {0}
      run: |
        conda install pip
        conda install hdf4
        conda install -c conda-forge pyhdf
        pip install -e .
    - name: Install mlclouds dependencies
      working-directory: ./mlclouds
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: Run nsrdb pytest
      working-directory: ./nsrdb
      shell: bash -l {0}
      run: |
        conda install pytest
        pytest -v --disable-warnings
