name: Pytests

on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
        include:
          - os: ubuntu-latest
            python-version: 3.9

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install nsrdb dependencies
      run: |
        python -m pip install --upgrade pip
        conda install hdf4
        python -m pip install pyhdf
        python -m pip install pytest
        python -m pip install pytest-cov
        python -m pip install .
    - name: Run pytest
      run: |
        python -m pytest -v --disable-warnings
